{{- $root := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transcoder-chunk-saver.fullname" . }}
  labels:
  {{- include "transcoder-chunk-saver.labels" . | nindent 4 }}
data:
  appsettings.json: |-
{{ tpl ($.Files.Get "appsettings.json") $ | indent 4}}